name: cheer-up-your-colleagues


x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-06-06T09-36-42Z
  command: server --console-address ":9001" http://minio/data{1...2}
  expose:
    - "9000"
    - "9001"
  # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5


services:
  minio:
    <<: *minio-common
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data-1:/data1
      - data-2:/data2


volumes:
  data-1:
  data-2:
